#define IDD_ABOUT  2900

#define IDT_ABOUT_INFO  2901
#define IDT_ABOUT_FORK_NOTE  2902
#define IDS_ABOUT_FORK_REPO  2903

#define IDI_LOGO             100
#define IDT_ABOUT_VERSION    101
#define IDT_ABOUT_DATE       102
#define IDT_ABOUT_FORK_VERSION  103
#define IDT_ABOUT_FORK_DATE     104
#define IDT_ABOUT_FORK_COPYRIGHT 105
#define IDT_ABOUT_FORK_INFO     106
#define IDB_ABOUT_HOMEPAGE   110
#define IDB_ABOUT_FORK_REPO  111
